cookietemple_version: '1.4.1 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: bchtracer
project_slug_no_hyphen: bchtracer
template_version: '2.1.1 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: hosseinzoda
creator_github_username: hosseinzoda
is_github_repo: false
is_repo_private: false
is_github_orga: false
full_name: Hossein Zoda
email: hosseinzoda@gmail.com
project_name: bchtracer
project_short_description: A simple analytics tool for reading bch's blockchain
version: 0.1.0
license: MIT
